### ISSUE TITLE
Correction on pm.sublime-settings

### ISSUE THREAD

**Issue by jsmedmar** [randy3k/Project-Manager#23]
I don't know if this is a local difference, however, I was able to discover the hostname with:

sys.modules['Project Manager'].pm.get_node()

instead of (note the hyphen in the key):

sys.modules['Project-Manager'].pm.get_node()

**Comment by randy3k** [comment]
Thanks for pointing it out.
It depends how the user installed Project Manager. If one installed it via Package Control, they should use  `sys.modules['Project Manager'].pm.get_node()`. While if they installed it by cloning the repository, they should use `sys.modules['Project-Manager'].pm.get_node()`.

**Comment by randy3k** [comment]
Since more uses are using Package Control, I will update the comment.

**Comment by JuanSanMedina** [comment]
Hello @randy3k, (I don't want to create a new issue because I suspect this is local):

I'm getting:

 File "pm in <path to>/Installed Packages/Project Manager.sublime-package", line 91, in get_projects_info
TypeError: 'NoneType' object is not iterable

My Project - <HosName> folder has a library.json that looks perfectly ok. When I put the same library.json file in Projects/library.json, pm works perfectly, however in the local project folder it does not.

**Comment by randy3k** [comment]
Did you upgrade to the latest version 0.5.6? I think it should been fixed.

**Comment by JuanSanMedina** [comment]
I did.

**Comment by randy3k** [comment]
Is your `projects_fpath` setting empty? I cannot think of any reasons of failing at line 91...

**Comment by JuanSanMedina** [comment]
my pm settings look like this, 

{
    "use_local_projects_dir": true,
}

I dont have any custom projects_fpath...

**Comment by randy3k** [comment]
Can you also try remove and reinstalling Project Manager?

**Comment by JuanSanMedina** [comment]
I figured that the error --- TypeError: 'NoneType' object is not iterable --- happens when the library.json file is empty, the content needs to be at least: "[]".

So it seems that what is happening is that it loads the local library but then automatically reloads the default library:

(terminal print when cmd + ^ + p) ->

Reloading .../Sublime/ST3/User/Projects - JuanSanMedina/library.json
Reloading .../Sublime/ST3/User/Projects/library.json

**Comment by randy3k** [comment]
It is strange that you have `Reloading .../Sublime/ST3/User/Projects/library.json` and your Sublime Text is looking for changes on .json files

**Comment by randy3k** [comment]
Are you using build 3065?

**Comment by JuanSanMedina** [comment]
yes

**Comment by JuanSanMedina** [comment]
Ok, Randy, I'll try to figure this out. If I succeed, I'll post it here.

**Comment by randy3k** [comment]
By the way, is it a Mac or Linux?

**Comment by JuanSanMedina** [comment]
Mac

**Comment by randy3k** [comment]
I suspect reloading command is the reason, it shouldn't be there. And I have no clue why it shows up

**Comment by JuanSanMedina** [comment]
It was showing up because I had the library.json files opened. So it has nothing to do with the pm issue.

**Comment by JuanSanMedina** [comment]
In conlusion, the issue is that pm does not load the library.json file inside Projects - HostName when pm setting is {"use_local_projects_dir": true,}

**Comment by JuanSanMedina** [comment]
And i think is a machine issue, because yesterday it was working perfectly fine in my machine at work.

**Comment by randy3k** [comment]
Just want to clarify, PM menu is not popping up no matter what the content of library.json is?

**Comment by JuanSanMedina** [comment]
yes, pm menu pops up but empty, regardless the content of library.json in Projects - HostName/. If the same library.json is moved to Projects/ it the pm menu shows up with the correct content.

**Comment by randy3k** [comment]
does your HostName only contain english characters or numbers?

**Comment by JuanSanMedina** [comment]
when i do .get_node() the hostname is JuanSanMedina

**Comment by jsmedmar** [comment]
Hi @randy3k after the Sublime's last upgrade, the plugin is working perfectly fine. Please close the issue.

**Comment by randy3k** [comment]
great
