### ISSUE TITLE
Options to open a new project removed from the fast menu

### ISSUE THREAD

**Issue by ibc** [randy3k/Project-Manager#40]
Why? Now when I press `ctrl+cmd+p` (OSX) I just see the list of my projects, and choosing one of them means closing the current project and replacing it with the new one. That's not what I want in 99% of cases.

Previously, `ctrl+cmd+p` displayed also options such as "Open in a new window" and so on. Now instead I need to go to the main menu via `shift+cmd+p` and choose `Project Manager` which is slower.

**Comment by ibc** [comment]
I think the behavior was changed in https://github.com/randy3k/Project-Manager/commit/f3ed7ce36857f6a1eab86aa88291ad0fdde8047c

**Comment by randy3k** [comment]
The new design is adopted to mimic the Project Manager of atom and the original Sublime Text "Quick Switch Project". In order to open project in new window quickly, you can add [this](https://github.com/randy3k/Project-Manager#optional-keybind) keybind. Alternatively,
you can open a new window "super+shift+n", then "super+ctrl+p".

**Comment by ibc** [comment]
Thanks a lot, very useful.
